### ISSUE TITLE
FIXME

### ISSUE THREAD

**Issue by nidare30** [IUT-MemScanner/nixwen#3]
*  problème alter lorsqu'on veut mettre une valeur > 9 
  *  premier search, la valeur recherchée ne s'y trouve pas
  *  lors de search les premières valeurs affichées ne sont pas cohérentes

**Comment by EnzDev** [comment]
Pas cohérentes ?
Précise ce que tu as fait ainsi que les résultats obtenus.

**Comment by nidare30** [comment]
on nous retourne des pointeur qui ne devrait pas  33 new 4267402848 il n'y a pas 33 de moins 

j'ai un peu de mal a expliquer sa mieu --'

``` bash
> cont
> stop
> search 
0 : +   the value is greater
1 : +?  the value is greater by
2 : -   the value is lower
3 : -?  the value is lower by
4 : =   the value is the same
5 : /=  the value has changed
6 : ><  in between comparison
Choix du mode : 3
Entrez une valeur de changement : 33
> list
Entrez le nombre de valeurs souhaitée : 30
0 : (0x8fdf28) 33 new 4267402848
1 : (0x8fdf98) 33 new 1
2 : (0x9a6c38) 33 new 33
3 : (0xa480f8) 33 new 33
4 : (0xa48118) 33 new 33
5 : (0xa48138) 33 new 33
6 : (0x7ffde7a8d6d8) 75 new 42
```

il y a que la 6 qui arrai du etre la (et qui est la valeur que je recherchai)

**Comment by EnzDev** [comment]
C'est ton dernier changement qui fait ça (avec old) parce que ici, tant que tu n'as pas fait `cont` tu devrais obtenir les mêmes valeurs du côté droit et gauche puisque new fait une *live capture* des valeurs et n'a donc aucun rapport. Si ce n'est pas ça alors je n'ai pas compris.

**Comment by EnzDev** [comment]
Ha si, j'ai compris affiche ton oldmap et la nouvelle, compare les tailles.
Tes valeurs qui sont *incorrectes* on en fait bien été supprimées mais comme tu affiche l'ancienne bah elle reste là.

**Comment by nidare30** [comment]
ok mais faut quand meme pouvoir afficher l'ancienne valeur :/ faudrait link les deux
ou cré une map de tableau ou list )

**Comment by EnzDev** [comment]
C'est déjà celle qui est affichée, comme tu as vu sur le rapport, les données inscrites sont : 
 **numéro (pointeur)** : **valeurs trouvée pendant la recherche** new **valeur actuelle dans le programme**
